name: example-group
pools:
  - name: production
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 3
      memory: 10Gi
  - name: other
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 2
      memory: 6Gi